
spring:
  flyway:
    locations: classpath:db/migration
    schemas: demo
  docker:
    compose:
      file: ./demoj-spring-framework-all/demoj-spring-boot-docker-compose/compose.yaml
  datasource:
#    url: jdbc:mysql://mysql:3306/demo?serverTimezone=UTC&allowPublicKeyRetrieval=false
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.czx.demo.spring.boot.dockerCompose.entity
  #  config-location: classpath:/config/mybatis-config.xml
  mapperLocations: classpath:/db/mapper/*.xml
