services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - ${MYSQL_HOST_PORT}:3306
    labels:
      org.springframework.boot.service-connection: mysql
      org.springframework.boot.jdbc.parameters: 'serverTimezone=UTC&allowPublicKeyRetrieval=false'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - 'D:\\my-dev\\demo-java\\spring-boot-docker-compose\\docker-volume:/var/lib/mysql'