services:

  mysql:
    image: 'mysql:5.7'
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3306:3306'
    labels:
      org.springframework.boot.service-connection: mysql
      org.springframework.boot.jdbc.parameters: serverTimezone=UTC&allowPublicKeyRetrieval=false
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
      MYSQL_USER_NAME: czx
      MYSQL_USER_PASSWORD: 123456
    volumes:
      - 'D:\\my-dev\\demo-java\\spring-boot-docker-compose\\docker-volume:/var/lib/mysql'
    networks:
      - app-network

  app:
    depends_on:
      - mysql
    build: ./
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port": ${SPRING_DOCKER_PORT},
          "spring.datasource.url": "jdbc:mysql://mysql:3306/demo?serverTimezone=UTC&allowPublicKeyRetrieval=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "${MYSQL_ROOT_PASSWORD}"
        }'
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
